In [26]:
import pandas as pd

Dados retirados de https://github.com/datadista/datasets/tree/master/COVID%2019. As fontes utilizadas são o Ministerio de Sanidad, Consumo y Bienestar Social, Departamento de Seguridad Nacional, Instituto de Salud Carlos III e do Ministerio de Transportes  Movilidad y Agenda Urbana da Espanha. A base de dados contém informações sobre o número de casos e mortes diários por região da Espanha e é atualizada diariamente.

O código a seguir realiza a importação do GitHub desses dados, realiza algumas manipulações em sua estrutura e gera quatro arquivos .csv  de maneira a indicar, respectivamente, casos e mortes por COVID-19 na Espanha, acumulados e diários, a nível de estado.

# Casos na Espanha

In [27]:
url = 'https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/ccaa_covid19_casos.csv'
data_spain = pd.read_csv(url, error_bad_lines=False)
data_spain.drop(data_spain.columns[[0]],axis=1,inplace=True)
data_spain

,CCAA,2020-02-27,2020-02-28,2020-02-29,2020-03-01,2020-03-02,2020-03-03,2020-03-04,2020-03-05,2020-03-06,...,2020-03-30,2020-03-31,2020-04-01,2020-04-02,2020-04-03,2020-04-04,2020-04-05,2020-04-06,2020-04-07,2020-04-08
0,Andalucía,1,6,8,12,12,13,13,12,21,...,5405,5818,6392,6972,7374,7869,8301,8581,8767,8997
1,Aragón,0,1,1,0,0,0,0,1,6,...,2078,2272,2491,2700,2889,3078,3232,3347,3449,3549
2,Asturias,0,0,0,1,1,1,2,5,5,...,1158,1236,1322,1384,1433,1522,1605,1646,1679,1705
3,Baleares,1,1,2,2,2,2,5,6,6,...,1000,1069,1131,1204,1257,1271,1293,1320,1369,1412
4,Canarias,6,6,6,7,7,7,7,8,11,...,1204,1262,1380,1444,1490,1564,1622,1649,1725,1762
5,Cantabria,0,0,0,1,10,10,10,10,10,...,1100,1171,1213,1268,1321,1384,1441,1483,1501,1572
6,Castilla-La Mancha,0,0,0,1,3,7,12,13,15,...,5858,6424,7047,7682,8523,9324,10031,10602,11077,11788
7,Castilla y León,0,2,2,3,3,8,11,11,14,...,5801,6211,6847,7355,7875,8332,8749,9116,9581,10058
8,Cataluña,2,3,5,6,15,15,15,24,24,...,16157,18773,19991,21804,23460,24734,26032,26824,28323,29647
9,Ceuta,0,0,0,0,0,0,0,0,0,...,25,34,51,55,62,73,83,83,83,84
10,C. Valenciana,2,8,10,15,15,15,19,19,30,...,5110,5508,5922,6308,6624,6901,7184,7334,7443,7655
11,Extremadura,0,0,0,4,6,6,6,6,6,...,1560,1628,1679,1837,1893,1979,2047,2068,2116,2184
12,Galicia,0,0,0,0,0,0,1,1,3,...,3723,4039,4432,4842,5219,5625,5944,6151,6331,6538
13,Madrid,4,5,8,10,29,49,70,90,137,...,24090,27509,29840,32155,34188,36249,37584,38723,40469,42450
14,Melilla,0,0,0,0,0,0,0,0,0,...,51,54,62,62,70,79,83,86,92,93
15,Murcia,0,0,0,0,0,0,0,0,0,...,939,974,1041,1084,1145,1188,1235,1259,1283,1326
16,Navarra,0,0,0,1,1,1,3,3,3,...,2146,2305,2497,2682,2836,2972,3073,3231,3355,3467
17,País Vasco,0,0,2,3,9,13,17,17,45,...,6057,6320,6838,7317,7827,8187,8628,8810,9021,9452
18,La Rioja,0,0,0,0,1,3,7,11,29,...,1733,1810,1960,2083,2224,2405,2592,2719,2846,2951
19,Total,16,32,44,66,114,150,198,237,365,...,85195,94417,102136,110238,117710,124736,130759,135032,140510,146690

In [28]:
data_spain = data_spain.transpose()
data_spain = data_spain.rename(columns=data_spain.iloc[0]).drop(data_spain.index[0])
data_spain_daily = data_spain.diff()
data_spain_daily

,Andalucía,Aragón,Asturias,Baleares,Canarias,Cantabria,Castilla-La Mancha,Castilla y León,Cataluña,Ceuta,C. Valenciana,Extremadura,Galicia,Madrid,Melilla,Murcia,Navarra,País Vasco,La Rioja,Total
2020-02-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-02-28,5,1,0,0,0,0,0,2,1,0,6,0,0,1,0,0,0,0,0,16
2020-02-29,2,0,0,1,0,0,0,0,2,0,2,0,0,3,0,0,0,2,0,12
2020-03-01,4,-1,1,0,1,1,1,1,1,0,5,4,0,2,0,0,1,1,0,22
2020-03-02,0,0,0,0,0,9,2,0,9,0,0,2,0,19,0,0,0,6,1,48
2020-03-03,1,0,0,0,0,0,4,5,0,0,0,0,0,20,0,0,0,4,2,36
2020-03-04,0,0,1,3,0,0,5,3,0,0,4,0,1,21,0,0,2,4,4,48
2020-03-05,-1,1,3,1,1,0,1,0,9,0,0,0,0,20,0,0,0,0,4,39
2020-03-06,9,5,0,0,3,0,2,3,0,0,11,0,2,47,0,0,0,28,18,128
2020-03-07,6,5,0,0,7,0,0,0,0,0,0,0,0,37,0,0,0,0,10,65
2020-03-08,8,2,2,2,-1,2,0,8,25,0,7,0,2,28,0,1,0,57,16,159
2020-03-09,19,0,0,3,5,0,11,1,26,0,0,1,1,267,0,3,0,47,26,410
2020-03-10,17,25,15,2,3,0,13,33,49,0,13,1,16,313,0,5,9,46,63,623
2020-03-11,19,7,10,3,12,0,32,15,32,0,15,1,17,242,0,2,34,30,35,506
2020-03-12,25,19,15,6,14,4,44,21,104,0,11,10,-4,364,0,15,27,121,26,822
2020-03-13,104,16,20,8,19,13,79,77,56,0,18,20,50,602,2,9,57,71,38,1259
2020-03-14,50,0,25,-2,20,2,95,54,193,0,36,27,30,950,1,12,16,0,35,1544
2020-03-15,168,67,45,0,19,20,112,69,206,1,279,29,80,604,5,24,37,213,22,2000
2020-03-16,117,27,40,45,10,7,166,42,188,0,0,16,50,621,0,6,91,0,12,1438
2020-03-17,129,33,16,19,29,0,0,97,491,0,132,42,47,706,9,20,39,135,43,1987
2020-03-18,176,19,49,20,33,10,108,237,472,0,185,41,49,766,3,25,73,208,64,2538
2020-03-19,149,55,50,57,39,15,126,200,836,0,195,47,112,1140,3,45,96,217,49,3431
2020-03-20,279,79,52,34,67,61,243,279,568,4,184,56,125,388,1,37,72,275,29,2833
2020-03-21,228,64,142,43,61,71,379,319,933,0,258,57,161,1756,1,36,110,260,67,4946
2020-03-22,210,108,59,85,66,67,396,278,501,0,241,30,176,781,0,56,130,372,90,3646
2020-03-23,236,106,49,69,67,65,259,311,1221,1,297,109,293,873,3,49,92,324,93,4517
2020-03-24,510,120,68,78,76,78,387,405,1939,0,266,143,207,1777,0,40,128,307,55,6584
2020-03-25,539,149,117,84,100,85,315,480,2073,3,449,106,238,2245,10,92,183,543,126,7937
2020-03-26,396,209,62,98,127,161,603,548,1655,1,584,227,262,2569,1,119,214,675,67,8578
2020-03-27,387,222,59,95,94,139,551,644,1348,7,332,262,407,2077,3,118,230,655,241,7871
2020-03-28,484,254,104,107,147,127,578,659,1323,0,502,163,450,2277,3,88,188,535,200,8189
2020-03-29,405,266,84,96,100,86,734,623,763,4,750,62,367,1157,3,70,182,604,193,6549
2020-03-30,723,220,70,42,79,77,612,387,1131,4,326,104,584,1413,3,67,135,317,104,6398
2020-03-31,413,194,78,69,58,71,566,410,2616,9,398,68,316,3419,3,35,159,263,77,9222
2020-04-01,574,219,86,62,118,42,623,636,1218,17,414,51,393,2331,8,67,192,518,150,7719
2020-04-02,580,209,62,73,64,55,635,508,1813,4,386,158,410,2315,0,43,185,479,123,8102
2020-04-03,402,189,49,53,46,53,841,520,1656,7,316,56,377,2033,8,61,154,510,141,7472
2020-04-04,495,189,89,14,74,63,801,457,1274,11,277,86,406,2061,9,43,136,360,181,7026
2020-04-05,432,154,83,22,58,57,707,417,1298,10,283,68,319,1335,4,47,101,441,187,6023
2020-04-06,280,115,41,27,27,42,571,367,792,0,150,21,207,1139,3,24,158,182,127,4273
2020-04-07,186,102,33,49,76,18,475,465,1499,0,109,48,180,1746,6,24,124,211,127,5478
2020-04-08,230,100,26,43,37,71,711,477,1324,1,212,68,207,1981,1,43,112,431,105,6180

Geração de dois arquivos .csv

In [29]:
data_spain.to_csv('covid19-spain-region-cases-acc.csv')
data_spain_daily.to_csv('covid19-spain-region-cases-daily.csv')

# Mortes na Espanha

In [34]:
url2 = 'https://raw.githubusercontent.com/datadista/datasets/master/COVID%2019/ccaa_covid19_fallecidos.csv'
data_spain_deaths = pd.read_csv(url2, error_bad_lines=False)
data_spain_deaths.drop(data_spain_deaths.columns[[0]],axis=1,inplace=True)
data_spain_deaths

,CCAA,2020-03-03,2020-03-04,2020-03-05,2020-03-06,2020-03-07,2020-03-08,2020-03-09,2020-03-10,2020-03-11,...,2020-03-30,2020-03-31,2020-04-01,2020-04-02,2020-04-03,2020-04-04,2020-04-05,2020-04-06,2020-04-07,2020-04-08
0,Andalucía,0,0,0,0,0,0,0,0,0,...,236,248,308,343,376,426,470,491,528,605
1,Aragón,0,0,0,1,1,2,2,3,4,...,106,138,169,200,224,251,270,284,312,349
2,Asturias,0,0,0,0,0,0,0,0,0,...,49,55,63,69,70,76,80,86,96,102
3,Baleares,0,0,0,0,0,0,0,0,0,...,37,42,46,58,69,71,75,81,84,89
4,Canarias,0,0,0,0,0,0,0,0,0,...,40,55,62,68,73,78,80,85,89,91
5,Cantabria,0,0,0,0,0,0,0,0,0,...,27,37,54,60,64,68,68,77,85,92
6,Castilla-La Mancha,0,0,0,0,0,0,0,0,0,...,622,708,774,854,916,989,1055,1132,1177,1255
7,Castilla y León,0,0,0,0,0,0,0,0,0,...,442,516,585,641,723,786,847,919,982,1028
8,Cataluña,0,0,0,0,1,1,1,3,3,...,1410,1672,1849,2093,2335,2508,2637,2760,2908,3041
9,Ceuta,0,0,0,0,0,0,0,0,0,...,1,1,1,1,1,1,2,3,4,4
10,C. Valenciana,0,1,1,1,1,1,1,1,1,...,310,339,395,443,511,571,613,637,672,724
11,Extremadura,0,0,0,0,0,0,0,0,0,...,106,133,152,181,200,208,218,228,258,271
12,Galicia,0,0,0,0,0,0,0,0,0,...,66,84,103,120,138,159,174,190,204,213
13,Madrid,0,0,1,2,4,8,8,21,31,...,3392,3603,3865,4175,4483,4723,4941,5136,5371,5586
14,Melilla,0,0,0,0,0,0,0,0,0,...,1,1,1,1,2,2,2,2,2,2
15,Murcia,0,0,0,0,0,0,0,0,0,...,25,34,37,42,46,51,59,68,78,85
16,Navarra,0,0,0,0,0,0,0,0,0,...,102,113,130,141,151,171,178,187,202,206
17,País Vasco,0,0,1,1,1,5,5,6,6,...,297,325,369,412,444,477,515,548,586,635
18,La Rioja,0,0,0,0,0,0,0,1,2,...,71,85,90,101,109,128,134,141,160,177
19,Total,0,1,3,5,8,17,17,35,47,...,7340,8189,9053,10003,10935,11744,12418,13055,13798,14555

In [35]:
data_spain_deaths = data_spain_deaths.transpose()
data_spain_deaths = data_spain_deaths.rename(columns=data_spain_deaths.iloc[0]).drop(data_spain_deaths.index[0])
data_spain_deaths_daily = data_spain_deaths.diff()
data_spain_deaths_daily

,Andalucía,Aragón,Asturias,Baleares,Canarias,Cantabria,Castilla-La Mancha,Castilla y León,Cataluña,Ceuta,C. Valenciana,Extremadura,Galicia,Madrid,Melilla,Murcia,Navarra,País Vasco,La Rioja,Total
2020-03-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2020-03-04,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1
2020-03-05,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,2
2020-03-06,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,2
2020-03-07,0,0,0,0,0,0,0,0,1,0,0,0,0,2,0,0,0,0,0,3
2020-03-08,0,1,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,4,0,9
2020-03-09,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2020-03-10,0,1,0,0,0,0,0,0,2,0,0,0,0,13,0,0,0,1,1,18
2020-03-11,0,1,0,0,0,0,0,0,0,0,0,0,0,10,0,0,0,0,1,12
2020-03-12,0,2,1,1,0,0,1,0,1,0,0,1,0,25,0,0,0,5,0,37
2020-03-13,0,1,0,0,0,0,4,1,0,0,0,0,0,25,0,0,0,3,0,36
2020-03-14,2,0,0,0,1,0,1,2,2,0,3,1,0,5,0,0,0,0,1,16
2020-03-15,4,0,0,0,0,0,4,3,2,0,1,0,2,127,0,0,0,9,0,152
2020-03-16,1,4,0,0,0,0,7,3,4,0,0,0,0,0,0,0,1,0,1,21
2020-03-17,4,1,0,0,1,0,0,3,6,0,8,1,1,142,0,0,1,13,1,182
2020-03-18,8,1,0,0,1,1,11,10,23,0,9,3,0,35,0,0,1,4,0,107
2020-03-19,4,2,0,1,0,0,14,7,14,0,2,2,1,108,0,0,1,13,0,169
2020-03-20,7,2,1,0,1,0,0,14,27,0,9,2,1,130,0,0,1,18,2,235
2020-03-21,10,5,3,2,3,1,42,12,40,0,17,2,4,176,0,1,4,14,8,324
2020-03-22,7,2,3,0,2,3,28,19,69,0,19,2,3,217,0,0,5,12,3,394
2020-03-23,11,8,4,6,2,1,33,28,54,0,25,4,6,242,0,1,10,23,4,462
2020-03-24,29,5,10,0,5,3,71,22,37,0,21,8,2,272,0,1,7,13,8,514
2020-03-25,26,3,3,3,5,5,47,41,234,0,28,13,7,290,0,2,2,22,7,738
2020-03-26,21,8,2,4,3,3,53,41,156,0,24,19,5,265,1,3,16,25,6,655
2020-03-27,10,10,2,5,3,4,51,46,208,0,31,11,11,322,0,7,9,27,12,769
2020-03-28,31,0,4,4,9,1,81,69,190,1,36,19,4,345,0,2,12,14,10,832
2020-03-29,32,35,8,3,3,4,91,59,156,0,33,12,13,325,0,3,14,44,3,838
2020-03-30,29,13,8,8,1,1,83,62,184,0,43,6,6,310,0,5,18,32,3,812
2020-03-31,12,32,6,5,15,10,86,74,262,0,29,27,18,211,0,9,11,28,14,849
2020-04-01,60,31,8,4,7,17,66,69,177,0,56,19,19,262,0,3,17,44,5,864
2020-04-02,35,31,6,12,6,6,80,56,244,0,48,29,17,310,0,5,11,43,11,950
2020-04-03,33,24,1,11,5,4,62,82,242,0,68,19,18,308,1,4,10,32,8,932
2020-04-04,50,27,6,2,5,4,73,63,173,0,60,8,21,240,0,5,20,33,19,809
2020-04-05,44,19,4,4,2,0,66,61,129,1,42,10,15,218,0,8,7,38,6,674
2020-04-06,21,14,6,6,5,9,77,72,123,1,24,10,16,195,0,9,9,33,7,637
2020-04-07,37,28,10,3,4,8,45,63,148,1,35,30,14,235,0,10,15,38,19,743
2020-04-08,77,37,6,5,2,7,78,46,133,0,52,13,9,215,0,7,4,49,17,757

Geração de dois arquivos .csv

In [36]:
data_spain_deaths.to_csv('covid19-spain-region-deaths-acc.csv')
data_spain_deaths_daily.to_csv('covid19-spain-region-deaths-daily.csv')